/********************************************************************
* G__Centrality.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__Centrality.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Centrality();
extern void G__cpp_setup_inheritanceG__Centrality();
extern void G__cpp_setup_typetableG__Centrality();
extern void G__cpp_setup_memvarG__Centrality();
extern void G__cpp_setup_globalG__Centrality();
extern void G__cpp_setup_memfuncG__Centrality();
extern void G__cpp_setup_funcG__Centrality();
extern void G__set_cpp_environmentG__Centrality();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/CentralityDetectorEvent.h"
#include "include/CentralityEventContainer.h"
#include "include/CentralitySlicesFinder.h"
#include "include/CentralityGetter.h"
#include "include/NA61DataEvent.h"
#include "include/NA61DataEventNew.h"
#include "include/CentralityManager.h"
#include "include/CentralitySlice.h"
#include "include/TreeInterface.h"
#include "include/CentralityContainerNormalizer.h"
#include "Glauber/GlauberFitter.h"
#include "Glauber/GlauberParGetter.h"
#include "Glauber/AliGlauberMC.h"
#include "Glauber/AliGlauberNucleon.h"
#include "Glauber/AliGlauberNucleus.h"
#include "InputTree/DataTreeBPD.h"
#include "InputTree/DataTreeConstants.h"
#include "InputTree/DataTreeConverterNA61.h"
#include "InputTree/DataTreeEvent.h"
#include "InputTree/DataTreeMCTrack.h"
#include "InputTree/DataTreePSDModule.h"
#include "InputTree/DataTreePSDSection.h"
#include "InputTree/DataTreeSTSTrack.h"
#include "InputTree/DataTreeTOFHit.h"
#include "InputTree/DataTreeTrack.h"
#include "InputTree/DataTreeTrigger.h"
#include "InputTree/DataTreeV0Candidate.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__CentralityLN_TClass;
extern G__linked_taginfo G__G__CentralityLN_TBuffer;
extern G__linked_taginfo G__G__CentralityLN_TMemberInspector;
extern G__linked_taginfo G__G__CentralityLN_TObject;
extern G__linked_taginfo G__G__CentralityLN_TNamed;
extern G__linked_taginfo G__G__CentralityLN_TString;
extern G__linked_taginfo G__G__CentralityLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__CentralityLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CentralityLN_TObjArray;
extern G__linked_taginfo G__G__CentralityLN_TClonesArray;
extern G__linked_taginfo G__G__CentralityLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__CentralityLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CentralityLN_CentralityDetectorEvent;
extern G__linked_taginfo G__G__CentralityLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__G__CentralityLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CentralityLN_CentralityEventContainer;
extern G__linked_taginfo G__G__CentralityLN_vectorlECentralityDetectorEventcOallocatorlECentralityDetectorEventgRsPgR;
extern G__linked_taginfo G__G__CentralityLN_reverse_iteratorlEvectorlECentralityDetectorEventcOallocatorlECentralityDetectorEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CentralityLN_TCut;
extern G__linked_taginfo G__G__CentralityLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__CentralityLN_TTree;
extern G__linked_taginfo G__G__CentralityLN_TFile;
extern G__linked_taginfo G__G__CentralityLN_TBranch;
extern G__linked_taginfo G__G__CentralityLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__CentralityLN_TF1;
extern G__linked_taginfo G__G__CentralityLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__CentralityLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__CentralityLN_TH1F;
extern G__linked_taginfo G__G__CentralityLN_TGraphErrors;
extern G__linked_taginfo G__G__CentralityLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__G__CentralityLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__G__CentralityLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CentralityLN_TCanvas;
extern G__linked_taginfo G__G__CentralityLN_CentralitySlice;
extern G__linked_taginfo G__G__CentralityLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__G__CentralityLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CentralityLN_CentralitySlicesFinder;
extern G__linked_taginfo G__G__CentralityLN_GlauberParGetter;
extern G__linked_taginfo G__G__CentralityLN_CentralityGetter;
extern G__linked_taginfo G__G__CentralityLN_TChain;
extern G__linked_taginfo G__G__CentralityLN_NA61DataEvent;
extern G__linked_taginfo G__G__CentralityLN_DataTreeTrack;
extern G__linked_taginfo G__G__CentralityLN_DataTreePSDSection;
extern G__linked_taginfo G__G__CentralityLN_DataTreePSDModule;
extern G__linked_taginfo G__G__CentralityLN_DataTreeTOFHit;
extern G__linked_taginfo G__G__CentralityLN_DataTreeV0Candidate;
extern G__linked_taginfo G__G__CentralityLN_DataTreeMCTrack;
extern G__linked_taginfo G__G__CentralityLN_DataTreeTrigger;
extern G__linked_taginfo G__G__CentralityLN_DataTreeBPD;
extern G__linked_taginfo G__G__CentralityLN_DataTreeEvent;
extern G__linked_taginfo G__G__CentralityLN_NA61DataEventNew;
extern G__linked_taginfo G__G__CentralityLN_CentralityManager;
extern G__linked_taginfo G__G__CentralityLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__CentralityLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CentralityLN_TreeInterface;
extern G__linked_taginfo G__G__CentralityLN_CentralityContainerNormalizer;
extern G__linked_taginfo G__G__CentralityLN_GlauberFitter;
extern G__linked_taginfo G__G__CentralityLN_AliGlauberNucleus;
extern G__linked_taginfo G__G__CentralityLN_TNtuple;
extern G__linked_taginfo G__G__CentralityLN_AliGlauberMC;
extern G__linked_taginfo G__G__CentralityLN_AliGlauberMCcLcLEdNdEtaType;
extern G__linked_taginfo G__G__CentralityLN_AliGlauberNucleon;
extern G__linked_taginfo G__G__CentralityLN_DataTreeConverterNA61;
extern G__linked_taginfo G__G__CentralityLN_DataTreeSTSTrack;

/* STUB derived class for protected member access */
